apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::669264890847:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-15VNF0R1DSEPI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::669264890847:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-17T13:05:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1798"
  uid: bd4d653c-4f07-4c26-85ad-17c1dad23f5f
